[pytest]
log_cli = true
log_cli_level = INFO
log_cli_format = %(asctime)s | %(levelname)s | %(message)s
log_file = reports/logs/test.log
log_file_level = INFO
log_file_format = %(asctime)s | %(levelname)s | %(message)s
log_auto_indent = true
addopts = --html=reports/html/report.html --self-contained-html